In [1]:
import pandas as pd

# Food with the most/least of each macro, based on category

In [2]:
nutritionFactsDF = pd.read_csv("nndb_flat.csv")
nutritionFactsDF

,ID,FoodGroup,ShortDescrip,Descrip,CommonName,MfgName,ScientificName,Energy_kcal,Protein_g,Fat_g,...,Folate_USRDA,Niacin_USRDA,Riboflavin_USRDA,Thiamin_USRDA,Calcium_USRDA,Copper_USRDA,Magnesium_USRDA,Phosphorus_USRDA,Selenium_USRDA,Zinc_USRDA
0,1001,Dairy and Egg Products,"BUTTER,WITH SALT","Butter, salted",NaN,NaN,NaN,717.0,0.85,81.11,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000000,0.004762,0.034286,0.018182,0.008182
1,1002,Dairy and Egg Products,"BUTTER,WHIPPED,WITH SALT","Butter, whipped, with salt",NaN,NaN,NaN,717.0,0.85,81.11,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000018,0.004762,0.032857,0.018182,0.004545
2,1003,Dairy and Egg Products,"BUTTER OIL,ANHYDROUS","Butter oil, anhydrous",NaN,NaN,NaN,876.0,0.28,99.48,...,0.0000,0.000188,0.003846,0.000833,0.003333,0.000001,0.000000,0.004286,0.000000,0.000909
3,1004,Dairy and Egg Products,"CHEESE,BLUE","Cheese, blue",NaN,NaN,NaN,353.0,21.40,28.74,...,0.0900,0.063500,0.293846,0.024167,0.440000,0.000044,0.054762,0.552857,0.263636,0.241818
4,1005,Dairy and Egg Products,"CHEESE,BRICK","Cheese, brick",NaN,NaN,NaN,371.0,23.24,29.68,...,0.0500,0.007375,0.270000,0.011667,0.561667,0.000027,0.057143,0.644286,0.263636,0.236364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,Finfish and Shellfish Products,"MACKEREL,SALTED","Fish, mackerel, salted",NaN,NaN,NaN,305.0,18.50,25.10,...,0.0375,0.206250,0.146154,0.016667,0.055000,0.000111,0.142857,0.362857,1.334545,0.100000
8614,90240,Finfish and Shellfish Products,"SCALLOP,(BAY&SEA),CKD,STMD","Mollusks, scallop, (bay and sea), cooked, steamed",NaN,NaN,NaN,111.0,20.54,0.84,...,0.0500,0.067250,0.018462,0.010000,0.008333,0.000037,0.088095,0.608571,0.394545,0.140909
8615,90480,Sweets,"SYRUP,CANE","Syrup, Cane",NaN,NaN,NaN,269.0,0.00,0.00,...,0.0000,0.006250,0.046154,0.108333,0.010833,0.000022,0.023810,0.011429,0.012727,0.017273
8616,90560,Finfish and Shellfish Products,"SNAIL,RAW","Mollusks, snail, raw",NaN,NaN,NaN,90.0,16.10,1.40,...,0.0150,0.087500,0.092308,0.008333,0.008333,0.000444,0.595238,0.388571,0.498182,0.090909
8617,93600,Finfish and Shellfish Products,"TURTLE,GREEN,RAW","Turtle, green, raw",NaN,NaN,NaN,89.0,19.80,0.50,...,0.0375,0.068750,0.115385,0.100000,0.098333,0.000278,0.047619,0.257143,0.305455,0.090909

In [3]:
nutritionFactsDF = nutritionFactsDF[['Protein','Fat', 'Sat.Fat', 'Fiber', 'Carbs']].replace({'t': 0})
nutritionFactsDF

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
0,Cows' milk,1 qt.,976,660,32,40,36,0,48,Dairy products
1,Milk skim,1 qt.,984,360,36,0,0,0,52,Dairy products
2,Buttermilk,1 cup,246,127,9,5,4,0,13,Dairy products
3,"Evaporated, undiluted",1 cup,252,345,16,20,18,0,24,Dairy products
4,Fortified milk,6 cups,"1,419","1,373",89,42,23,1.4,119,Dairy products
...,...,...,...,...,...,...,...,...,...,...
330,Fruit-flavored soda,12 oz.,346,161,0,0,0,0,42,"Drinks,Alcohol, Beverages"
331,Ginger ale,12 oz.,346,105,0,0,0,0,28,"Drinks,Alcohol, Beverages"
332,Root beer,12 oz.,346,140,0,0,0,0,35,"Drinks,Alcohol, Beverages"
333,Coffee,1 cup,230,3,0,0,0,0,1,"Drinks,Alcohol, Beverages"
334,Tea,1 cup,230,4,0,0,0,0,1,"Drinks,Alcohol, Beverages"

In [4]:
print(nutritionFactsDF.columns)

Index(['Food', 'Measure', 'Grams', 'Calories', 'Protein', 'Fat', 'Sat.Fat',
       'Fiber', 'Carbs', 'Category'],
      dtype='object')

In [6]:
# Convert Calories column data type
nutritionFactsDF['Calories'] = pd.to_numeric(nutritionFactsDF['Calories'], errors='coerce')

# Group by category and find the index of the food with the maximum protein content
caloriesIndex = nutritionFactsDF.groupby('Category')['Calories'].idxmax()

# Use the index to select the corresponding rows and create a new dataframe
topCaloriesDF = nutritionFactsDF.loc[caloriesIndex, ['Food', 'Category', 'Calories']]

# Reset the index of the new dataframe
topCaloriesDF = topCaloriesDF.reset_index(drop=True)

topCaloriesDF

                              Food                          Category  Calories
0                             Rice  Breads, cereals, fastfood,grains     748.0
1              (1/2 cup ice cream)                    Dairy products     690.0
2                   Puddings Sugar                  Desserts, sweets     770.0
3                             Beer         Drinks,Alcohol, Beverages     228.0
4                             Lard           Fats, Oils, Shortenings     992.0
5                          Oysters                     Fish, Seafood     231.0
6        Cranberry sauce sweetened                        Fruits A-F     530.0
7       Lemonade concentratefrozen                        Fruits G-P     430.0
8                Rhubarb sweetened                        Fruits R-Z     385.0
9   Brown, firm-packed, dark sugar                     Jams, Jellies     815.0
10                         Pot-pie                     Meat, Poultry     480.0
11                     Brazil nuts                    Seeds and Nuts     457.0
12                     Cream soups                             Soups     200.0
13               Lima, dry, cooked                    Vegetables A-E     260.0
14                         Lentils                    Vegetables F-P     212.0
15             Potatoes, pan-tried                    Vegetables R-Z     268.0

In [7]:
# Convert Protein column data type
nutritionFactsDF['Protein'] = pd.to_numeric(nutritionFactsDF['Protein'], errors='coerce')

# Group by category and find the index of the food with the maximum protein content
proteinIndex = nutritionFactsDF.groupby('Category')['Protein'].idxmax()

# Use the index to select the corresponding rows and create a new dataframe
topProteinDF = nutritionFactsDF.loc[proteinIndex, ['Food', 'Category', 'Protein']]

# Reset the index of the new dataframe
topProteinDF = topProteinDF.reset_index(drop=True)

topProteinDF

                 Food                          Category  Protein
0         Whole-wheat  Breads, cereals, fastfood,grains       48
1      Fortified milk                    Dairy products       89
2       Bread pudding                  Desserts, sweets       11
3                Beer         Drinks,Alcohol, Beverages        0
4              Butter           Fats, Oils, Shortenings      114
5             Oysters                     Fish, Seafood      232
6     Dried, uncooked                        Fruits A-F        4
7              Prunes                        Fruits G-P        3
8             Raisins                        Fruits R-Z        2
9               Honey                     Jams, Jellies        0
10             Turkey                     Meat, Poultry       27
11            Almonds                    Seeds and Nuts       13
12         Bean soups                             Soups        8
13  Lima, dry, cooked                    Vegetables A-E       16
14            Lentils                    Vegetables F-P       15
15           Soybeans                    Vegetables R-Z       22

In [8]:
# Convert Fat column data type
nutritionFactsDF['Fat'] = pd.to_numeric(nutritionFactsDF['Fat'], errors='coerce')

# Group by category and find the index of the food with the maximum protein content
fatIndex = nutritionFactsDF.groupby('Category')['Fat'].idxmax()

# Use the index to select the corresponding rows and create a new dataframe
topFatDF = nutritionFactsDF.loc[fatIndex, ['Food', 'Category', 'Fat']]

# Reset the index of the new dataframe
topFatDF = topFatDF.reset_index(drop=True)

topFatDF

                     Food                          Category    Fat
0       Baked with cheese  Breads, cereals, fastfood,grains   25.0
1             or whipping                    Dairy products   44.0
2         Chocolate fudge                  Desserts, sweets   14.0
3                    Beer         Drinks,Alcohol, Beverages    0.0
4                  Butter           Fats, Oils, Shortenings  115.0
5                 Oysters                     Fish, Seafood  233.0
6                 Avocado                        Fruits A-F   18.0
7              OlivesRipe                        Fruits G-P   13.0
8              Watermelon                        Fruits R-Z    1.0
9                   Honey                     Jams, Jellies    0.0
10              Salt pork                     Meat, Poultry   55.0
11            Brazil nuts                    Seeds and Nuts   47.0
12            Cream soups                             Soups   12.0
13  Navy, baked with pork                    Vegetables A-E    6.0
14                   Kale                    Vegetables F-P    1.0
15    Potatoes, pan-tried                    Vegetables R-Z   14.0

In [9]:
# Convert Sat.Fat column data type
nutritionFactsDF['Sat.Fat'] = pd.to_numeric(nutritionFactsDF['Sat.Fat'], errors='coerce')

# Group by category and find the index of the food with the maximum protein content
satFatIndex = nutritionFactsDF.groupby('Category')['Sat.Fat'].idxmax()

# Use the index to select the corresponding rows and create a new dataframe
topSatFatDF = nutritionFactsDF.loc[satFatIndex, ['Food', 'Category', 'Sat.Fat']]

# Reset the index of the new dataframe
topSatFatDF = topSatFatDF.reset_index(drop=True)

topSatFatDF

,Food,Category,Sat.Fat
0,Baked with cheese,"Breads, cereals, fastfood,grains",24.0
1,Cows' milk,Dairy products,36.0
2,Chocolate fudge,"Desserts, sweets",12.0
3,Beer,"Drinks,Alcohol, Beverages",0.0
4,Butter,"Fats, Oils, Shortenings",116.0
5,Oysters,"Fish, Seafood",234.0
6,Avocado,Fruits A-F,12.0
7,OlivesRipe,Fruits G-P,12.0
8,Raisins,Fruits R-Z,0.0
9,Honey,"Jams, Jellies",0.0
10,Pork sausage,"Meat, Poultry",40.0
11,roasted and salted,Seeds and Nuts,31.0
12,Cream soups,Soups,11.0
13,"Navy, baked with pork",Vegetables A-E,6.0
14,Kale,Vegetables F-P,0.0
15,Potatoes Mashed with milk and butter,Vegetables R-Z,11.0

In [10]:
# Convert Fiber column data type
nutritionFactsDF['Fiber'] = pd.to_numeric(nutritionFactsDF['Fiber'], errors='coerce')

# Group by category and find the index of the food with the maximum protein content
fiberIndex = nutritionFactsDF.groupby('Category')['Fiber'].idxmax()

# Use the index to select the corresponding rows and create a new dataframe
topFiberDF = nutritionFactsDF.loc[fiberIndex, ['Food', 'Category', 'Fiber']]

# Reset the index of the new dataframe
topFiberDF = topFiberDF.reset_index(drop=True)

topFiberDF

                       Food                          Category  Fiber
0               Whole-wheat  Breads, cereals, fastfood,grains   67.5
1            Fortified milk                    Dairy products    1.4
2                 Ice cream                  Desserts, sweets   10.0
3                      Beer         Drinks,Alcohol, Beverages    0.0
4                    Butter           Fats, Oils, Shortenings  117.0
5                   Oysters                     Fish, Seafood  235.0
6              Blackberries                        Fruits A-F    6.6
7                     Pears                        Fruits G-P    2.0
8                  Raw, red                        Fruits R-Z    5.0
9                  Molasses                     Jams, Jellies    8.0
10                Salt pork                     Meat, Poultry    0.0
11             Sesame seeds                    Seeds and Nuts    3.1
12              Cream soups                             Soups    1.2
13         Dandelion greens                    Vegetables A-E    3.2
14  Lambs quarters, steamed                    Vegetables F-P    3.2
15                 Soybeans                    Vegetables R-Z    3.2

In [11]:
# Convert Carbs column data type
nutritionFactsDF['Carbs'] = pd.to_numeric(nutritionFactsDF['Carbs'], errors='coerce')

# Group by category and find the index of the food with the maximum protein content
carbsIndex = nutritionFactsDF.groupby('Category')['Carbs'].idxmax()

# Use the index to select the corresponding rows and create a new dataframe
topCarbsDF = nutritionFactsDF.loc[carbsIndex, ['Food', 'Category', 'Carbs']]

# Reset the index of the new dataframe
topCarbsDF = topCarbsDF.reset_index(drop=True)

topCarbsDF

                              Food                          Category  Carbs
0             White, 20 slices, or  Breads, cereals, fastfood,grains  229.0
1                   Fortified milk                    Dairy products  119.0
2                   Puddings Sugar                  Desserts, sweets  199.0
3              Fruit-flavored soda         Drinks,Alcohol, Beverages   42.0
4                           Butter           Fats, Oils, Shortenings  118.0
5                          Oysters                     Fish, Seafood  236.0
6        Cranberry sauce sweetened                        Fruits A-F  142.0
7       Lemonade concentratefrozen                        Fruits G-P  112.0
8                Rhubarb sweetened                        Fruits R-Z   98.0
9   Brown, firm-packed, dark sugar                     Jams, Jellies  210.0
10                         Pot-pie                     Meat, Poultry   32.0
11               coconut sweetened                    Seeds and Nuts   26.0
12                      Bean soups                             Soups   30.0
13               Lima, dry, cooked                    Vegetables A-E   48.0
14                         Lentils                    Vegetables F-P   38.0
15                         Candied                    Vegetables R-Z   80.0

In [ ]:
nutritionFactsDF.rename (columns={
    'Sat.Fat' : 'Saturated Fat'
    
}, inplace=True)

In [ ]:
nutritionFactsDF.head()

In [ ]:
nutritionFactsDF.rename (index={
    '(cornstarch)': 'Cornstarch'
    'or whipping' : 'Whipping Cream'
    '(1/2 cup ice cream)': 'Half a cup of ice cream'
}, inplace=True)

In [ ]:
nutritionFactsDF.head()

In [ ]:
from pprint import pprint

In [ ]:
NutritionFactsDict = nutritionFactsDF.to_dict('records')
NutritionFactsDict

In [ ]:
from pymongo import MongoClient

In [ ]:
mongo = MongoClient(port=27017)

In [ ]:
db = mongo.nutritionFactsDB
nutritionFactsData = db.nutritionFactsData

In [ ]:
nutritionFactsData.insert_many(NutritionFactsDict)

In [ ]:
results = list(nutritionFactsData.find())

In [ ]:
for order in results:
    pprint(order)